name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Каждые 10 минут
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: https://weather-bot-g3ku.onrender.com
        run: |
          # Заменяем ВАШ_URL_RENDER на адрес вашего приложения (например, https://my-weather-bot.onrender.com)
          curl -f https://ВАШ_URL_RENDER.onrender.com || echo "Site is sleeping or down, but ping sent."
