name: Keep Render Alive

on:
  schedule:
    # Запуск каждые 10 минут (синтаксис cron: минута час день месяц день_недели)
    - cron: '*/10 * * * *'
  
  # Возможность ручного запуска для проверки
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    
    steps:
      - name: https://weather-bot-g3ku.onrender.com
        run: |
          # Заменяем ВАШ_URL_RENDER на адрес вашего приложения (например, https://my-weather-bot.onrender.com)
          curl -f https://ВАШ_URL_RENDER.onrender.com || echo "Site is sleeping or down, but ping sent."
